import { Roboto, Oswald } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/providers";
import Navbar from "@/components/navbar";
import { isModerator } from "@/lib/authorization";
import AdminNavbar from "./admin/_components/navbar";

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto",
});

const oswald = Oswald({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-oswald",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const moderator = await isModerator();
  return (
    <html lang="en" className={`${roboto.variable} ${oswald.variable}`}>
      <body className={roboto.className}>
        <Providers>
          <Navbar />
          {/* {moderator ? <AdminNavbar /> : ""} */}
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
