import { FilterContextProvider } from "./_context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProductsLayout({ children }) {
  return <FilterContextProvider>{children}</FilterContextProvider>;
}
